		<!-- Color changing footer showing team name and members -->
        <section class="quicklinks">
            <h2>Developers</h2>
            <p>Created by Peter, Leon, John, Stefan and Arka</p>
        </section>
		<!-- Bottom footer with links -->
        <footer>
            <div class="flex-footer">
				<!-- Contact details -->
                <div>
                    <h4>Contact any of us</h4>
                    <a href="mailto:103804645@student.swin.edu.au">Stefan Ralph</a>
                    <a href="mailto:103103232@student.swin.edu.au">Peter </a>
                    <a href="mailto:103808595@student.swin.edu.au">Leon</a>
                    <a href="mailto:103403903@student.swin.edu.au">John</a>
                    <a href="mailto:103804645@student.swin.edu.au">Arka</a>
                </div>
				<!-- Sitemap -->
                <div>
                    <h4>Sitemap</h4>
                    <a href="index.php">Home</a>
                    <a href="topic.php">Topic</a>
                    <a href="quiz.php">Quiz</a>
                    <a href="enhancements.php">CSS Enhancements</a>
                    <a href="phpenhancements.php">PHP</a>
                </div>
				<!-- Social media links -->
                <div>
                    <h4>Social Media</h4>
                    <a href="https://facebook.com">Facebook</a>
                    <a href="https://instagram.com">Instagram</a>
                    <a href="https://twitter.com">Twitter</a>
                    <a href="https://discord.com">Discord</a>
                </div>
            </div>
			<!-- Copyright notice -->
            <div>
                <p>All rights reserved to Developers &copy; 2022-2023</p>
            </div>
		</footer>
