        <header>
			<!-- Nav bar at top of all pages -->
            <nav>
                <a href="index.php">
                Home
                </a>
                <a href="topic.php">
                Topic
                </a>
                <a href="quiz.php">
                Quiz
                </a>
                <a href="enhancements.php">
                Enhancements
                </a>
            </nav>
			<!-- Yellow background header with team members and logo -->
            <div>
                <p class="header-title">Developers</p>
                <p>Created by Peter, Leon, John, Stefan and Arka</p>
            </div>
            <aside id="logo-box">
                <img src="images/logo1.png" id="logo" alt="Site logo">
            </aside>
        </header>