        <header>
			<!-- Nav bar at top of all pages -->
            <nav>
                <a href="index.php">
                Home
                </a>
                <a href="topic.php">
                Topic
                </a>
                <a href="quiz.php">
                Quiz
                </a>
                <a href="enhancements.php">
                Enhancements
                </a>
            </nav>
		</header>